print("\n")
print('**********************************************************')
print("* My name is Zoey                                        *")
print("* Family name Lutsky                                     *")
print("* Birthday:13/01/2011                                    *")
print("* School: Tihon Hadas, Grade:9 , Class:5                 *")
print("* My favorit subject:History                             *")
print('* My hobits are:singing, dansing listan music 24/7 hours *')
print('**********************************************************')